CREATE TABLE "pg-drizzle_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_baseline_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_baseline_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"baseline_id" integer NOT NULL,
	"task_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"plannedStartDate" date,
	"plannedEndDate" date,
	"estimatedHours" numeric(8, 2),
	"progress" integer DEFAULT 0,
	"isMilestone" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_baseline" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_baseline_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_organization_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_organization_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"role" varchar(50) DEFAULT 'member' NOT NULL,
	"joinedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"description" text,
	"slug" varchar(100) NOT NULL,
	"timezone" varchar(50) DEFAULT 'UTC' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "pg-drizzle_organization_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"status" varchar(50) DEFAULT 'planning' NOT NULL,
	"startDate" timestamp,
	"endDate" timestamp,
	"working_days" text[] DEFAULT '{"Mon","Tue","Wed","Thu","Fri"}'::text[] NOT NULL,
	"working_hours" json,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_resource_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_id" integer NOT NULL,
	"resource_id" integer NOT NULL,
	"assignedUnits" numeric(4, 2) DEFAULT '1',
	"assignedHours" numeric(8, 2),
	"cost" numeric(10, 2),
	"startDate" date,
	"endDate" date,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_availability" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_resource_availability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource_id" integer NOT NULL,
	"startDate" date NOT NULL,
	"endDate" date NOT NULL,
	"availabilityType" varchar(20) NOT NULL,
	"description" text,
	"isFullDay" boolean DEFAULT true NOT NULL,
	"startTime" time,
	"endTime" time,
	"isRecurring" boolean DEFAULT false NOT NULL,
	"recurringPattern" varchar(50),
	"recurringEndDate" date,
	"timeZone" varchar(50),
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_availability_exception" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" integer NOT NULL,
	"resource_id" integer NOT NULL,
	"exception_date" date NOT NULL,
	"start_time_utc" time,
	"end_time_utc" time,
	"hours_available" numeric(4, 2) NOT NULL,
	"hourly_rate" numeric(10, 2) NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"exceptionType" varchar(20) NOT NULL,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_day_type_rate" (
	"resource_id" integer NOT NULL,
	"dayType" varchar(20) NOT NULL,
	"baseHourlyRate" numeric(10, 2) NOT NULL,
	"overtimeMultiplier" numeric(4, 2) DEFAULT '1.5',
	"currency" varchar(3) DEFAULT 'USD',
	"minimumHours" numeric(4, 2) DEFAULT '0',
	"maximumHours" numeric(4, 2),
	"effectiveDate" date DEFAULT now() NOT NULL,
	"expiryDate" date,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "resource_rate_unique" PRIMARY KEY("resource_id","dayType","effectiveDate")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_time_zone" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_resource_time_zone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource_id" integer NOT NULL,
	"timeZone" varchar(50) NOT NULL,
	"utcOffset" varchar(6),
	"isDST" boolean DEFAULT false NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"effectiveDate" date DEFAULT now() NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource_work_schedule" (
	"resource_id" integer NOT NULL,
	"dayOfWeek" integer NOT NULL,
	"dayType" varchar(20) DEFAULT 'regular' NOT NULL,
	"isWorkingDay" boolean DEFAULT true NOT NULL,
	"workStartTime" time,
	"workEndTime" time,
	"breakStartTime" time,
	"breakEndTime" time,
	"totalWorkHours" numeric(4, 2),
	"hourlyRate" numeric(10, 2),
	"currency" varchar(3) DEFAULT 'USD',
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "resource_schedule_unique" PRIMARY KEY("resource_id","dayOfWeek")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_resource" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_resource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organization_id" integer NOT NULL,
	"user_id" text,
	"name" varchar(256) NOT NULL,
	"type" varchar(50) DEFAULT 'human' NOT NULL,
	"hourlyRate" numeric(10, 2),
	"dailyWorkHours" numeric(4, 2) DEFAULT '8',
	"currency" varchar(3) DEFAULT 'USD',
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "pg-drizzle_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_task_dependency" (
	"predecessor_id" integer NOT NULL,
	"successor_id" integer NOT NULL,
	"dependencyType" varchar(20) DEFAULT 'fs' NOT NULL,
	"lag" integer DEFAULT 0,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "task_dep_unique" PRIMARY KEY("predecessor_id","successor_id")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"parent_id" integer,
	"name" varchar(256) NOT NULL,
	"description" text,
	"wbsCode" varchar(50),
	"status" varchar(50) DEFAULT 'not_started' NOT NULL,
	"progress" integer DEFAULT 0,
	"isMilestone" boolean DEFAULT false NOT NULL,
	"scheduledType" varchar(20) DEFAULT 'manual' NOT NULL,
	"plannedStartDate" date,
	"plannedEndDate" date,
	"actualStartDate" date,
	"actualEndDate" date,
	"duration" integer,
	"estimatedHours" numeric(8, 2),
	"actualHours" numeric(8, 2) DEFAULT '0',
	"constraintType" varchar(20),
	"constraintDate" date,
	"deadline" date,
	"priority" integer DEFAULT 0,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_time_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_time_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_id" integer NOT NULL,
	"resource_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"date" date NOT NULL,
	"startTime" time,
	"endTime" time,
	"hours" numeric(4, 2) NOT NULL,
	"dayType" varchar(20) DEFAULT 'regular' NOT NULL,
	"hourlyRate" numeric(10, 2),
	"cost" numeric(10, 2),
	"timeZone" varchar(50),
	"isOvertime" boolean DEFAULT false NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"organization_id" integer,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "pg-drizzle_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_account" ADD CONSTRAINT "pg-drizzle_account_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_baseline_task" ADD CONSTRAINT "pg-drizzle_baseline_task_baseline_id_pg-drizzle_baseline_id_fk" FOREIGN KEY ("baseline_id") REFERENCES "public"."pg-drizzle_baseline"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_baseline_task" ADD CONSTRAINT "pg-drizzle_baseline_task_task_id_pg-drizzle_task_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."pg-drizzle_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_baseline" ADD CONSTRAINT "pg-drizzle_baseline_project_id_pg-drizzle_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."pg-drizzle_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_organization_member" ADD CONSTRAINT "pg-drizzle_organization_member_organization_id_pg-drizzle_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_organization_member" ADD CONSTRAINT "pg-drizzle_organization_member_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_pg-drizzle_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_project" ADD CONSTRAINT "pg-drizzle_project_organization_id_pg-drizzle_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_assignment" ADD CONSTRAINT "pg-drizzle_resource_assignment_task_id_pg-drizzle_task_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."pg-drizzle_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_assignment" ADD CONSTRAINT "pg-drizzle_resource_assignment_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_availability" ADD CONSTRAINT "pg-drizzle_resource_availability_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_availability_exception" ADD CONSTRAINT "pg-drizzle_resource_availability_exception_organization_id_pg-drizzle_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_availability_exception" ADD CONSTRAINT "pg-drizzle_resource_availability_exception_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_day_type_rate" ADD CONSTRAINT "pg-drizzle_resource_day_type_rate_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_time_zone" ADD CONSTRAINT "pg-drizzle_resource_time_zone_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource_work_schedule" ADD CONSTRAINT "pg-drizzle_resource_work_schedule_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource" ADD CONSTRAINT "pg-drizzle_resource_organization_id_pg-drizzle_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_resource" ADD CONSTRAINT "pg-drizzle_resource_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_session" ADD CONSTRAINT "pg-drizzle_session_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_task_dependency" ADD CONSTRAINT "pg-drizzle_task_dependency_predecessor_id_pg-drizzle_task_id_fk" FOREIGN KEY ("predecessor_id") REFERENCES "public"."pg-drizzle_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_task_dependency" ADD CONSTRAINT "pg-drizzle_task_dependency_successor_id_pg-drizzle_task_id_fk" FOREIGN KEY ("successor_id") REFERENCES "public"."pg-drizzle_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_task" ADD CONSTRAINT "pg-drizzle_task_project_id_pg-drizzle_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."pg-drizzle_project"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_time_entry" ADD CONSTRAINT "pg-drizzle_time_entry_task_id_pg-drizzle_task_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."pg-drizzle_task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_time_entry" ADD CONSTRAINT "pg-drizzle_time_entry_resource_id_pg-drizzle_resource_id_fk" FOREIGN KEY ("resource_id") REFERENCES "public"."pg-drizzle_resource"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_time_entry" ADD CONSTRAINT "pg-drizzle_time_entry_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user" ADD CONSTRAINT "pg-drizzle_user_organization_id_pg-drizzle_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."pg-drizzle_organization"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "baseline_task_baseline_idx" ON "pg-drizzle_baseline_task" USING btree ("baseline_id");--> statement-breakpoint
CREATE INDEX "baseline_task_task_idx" ON "pg-drizzle_baseline_task" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "baseline_project_idx" ON "pg-drizzle_baseline" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "baseline_name_idx" ON "pg-drizzle_baseline" USING btree ("name");--> statement-breakpoint
CREATE INDEX "org_member_org_idx" ON "pg-drizzle_organization_member" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "org_member_user_idx" ON "pg-drizzle_organization_member" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "org_member_role_idx" ON "pg-drizzle_organization_member" USING btree ("role");--> statement-breakpoint
CREATE INDEX "organization_name_idx" ON "pg-drizzle_organization" USING btree ("name");--> statement-breakpoint
CREATE INDEX "organization_slug_idx" ON "pg-drizzle_organization" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "organization_timezone_idx" ON "pg-drizzle_organization" USING btree ("timezone");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "project_org_idx" ON "pg-drizzle_project" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "project_status_idx" ON "pg-drizzle_project" USING btree ("status");--> statement-breakpoint
CREATE INDEX "project_name_idx" ON "pg-drizzle_project" USING btree ("name");--> statement-breakpoint
CREATE INDEX "project_working_days_idx" ON "pg-drizzle_project" USING btree ("working_days");--> statement-breakpoint
CREATE INDEX "resource_assignment_task_idx" ON "pg-drizzle_resource_assignment" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "resource_assignment_resource_idx" ON "pg-drizzle_resource_assignment" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX "resource_assignment_dates_idx" ON "pg-drizzle_resource_assignment" USING btree ("startDate","endDate");--> statement-breakpoint
CREATE INDEX "resource_availability_resource_idx" ON "pg-drizzle_resource_availability" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX "resource_availability_dates_idx" ON "pg-drizzle_resource_availability" USING btree ("startDate","endDate");--> statement-breakpoint
CREATE INDEX "resource_availability_type_idx" ON "pg-drizzle_resource_availability" USING btree ("availabilityType");--> statement-breakpoint
CREATE INDEX "resource_availability_active_idx" ON "pg-drizzle_resource_availability" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "resource_exception_unique_idx" ON "pg-drizzle_resource_availability_exception" USING btree ("resource_id","exception_date");--> statement-breakpoint
CREATE INDEX "resource_exception_org_idx" ON "pg-drizzle_resource_availability_exception" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "resource_exception_date_idx" ON "pg-drizzle_resource_availability_exception" USING btree ("exception_date");--> statement-breakpoint
CREATE INDEX "resource_exception_active_idx" ON "pg-drizzle_resource_availability_exception" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "resource_rate_day_type_idx" ON "pg-drizzle_resource_day_type_rate" USING btree ("dayType");--> statement-breakpoint
CREATE INDEX "resource_rate_effective_idx" ON "pg-drizzle_resource_day_type_rate" USING btree ("effectiveDate");--> statement-breakpoint
CREATE INDEX "resource_rate_active_idx" ON "pg-drizzle_resource_day_type_rate" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "resource_timezone_resource_idx" ON "pg-drizzle_resource_time_zone" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX "resource_timezone_active_idx" ON "pg-drizzle_resource_time_zone" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "resource_timezone_effective_idx" ON "pg-drizzle_resource_time_zone" USING btree ("effectiveDate");--> statement-breakpoint
CREATE INDEX "resource_schedule_type_idx" ON "pg-drizzle_resource_work_schedule" USING btree ("dayType");--> statement-breakpoint
CREATE INDEX "resource_schedule_active_idx" ON "pg-drizzle_resource_work_schedule" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "resource_org_idx" ON "pg-drizzle_resource" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "resource_user_idx" ON "pg-drizzle_resource" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "resource_type_idx" ON "pg-drizzle_resource" USING btree ("type");--> statement-breakpoint
CREATE INDEX "resource_active_idx" ON "pg-drizzle_resource" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "task_dep_type_idx" ON "pg-drizzle_task_dependency" USING btree ("dependencyType");--> statement-breakpoint
CREATE INDEX "task_dep_predecessor_idx" ON "pg-drizzle_task_dependency" USING btree ("predecessor_id");--> statement-breakpoint
CREATE INDEX "task_dep_successor_idx" ON "pg-drizzle_task_dependency" USING btree ("successor_id");--> statement-breakpoint
CREATE INDEX "task_project_idx" ON "pg-drizzle_task" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "task_parent_idx" ON "pg-drizzle_task" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "task_status_idx" ON "pg-drizzle_task" USING btree ("status");--> statement-breakpoint
CREATE INDEX "task_wbs_idx" ON "pg-drizzle_task" USING btree ("wbsCode");--> statement-breakpoint
CREATE INDEX "task_milestone_idx" ON "pg-drizzle_task" USING btree ("isMilestone");--> statement-breakpoint
CREATE INDEX "time_entry_task_idx" ON "pg-drizzle_time_entry" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "time_entry_resource_idx" ON "pg-drizzle_time_entry" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX "time_entry_user_idx" ON "pg-drizzle_time_entry" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "time_entry_date_idx" ON "pg-drizzle_time_entry" USING btree ("date");--> statement-breakpoint
CREATE INDEX "time_entry_day_type_idx" ON "pg-drizzle_time_entry" USING btree ("dayType");--> statement-breakpoint
CREATE INDEX "time_entry_overtime_idx" ON "pg-drizzle_time_entry" USING btree ("isOvertime");